/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */







declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  AuthType: { // root type
    message?: string | null; // String
    token?: string | null; // String
    user?: NexusGenRootTypes['User'] | null; // User
  }
  Mutation: {};
  Product: { // root type
    creatorId: string; // String!
    id: string; // String!
    name: string; // String!
    price: number; // Float!
  }
  Query: {};
  User: { // root type
    email: string; // String!
    id: string; // String!
    isVerified: boolean; // Boolean!
    otp: string; // String!
    password: string; // String!
    refreshToken: string; // String!
    username: string; // String!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  AuthType: { // field return type
    message: string | null; // String
    token: string | null; // String
    user: NexusGenRootTypes['User'] | null; // User
  }
  Mutation: { // field return type
    accessToken: NexusGenRootTypes['AuthType']; // AuthType!
    createProduct: NexusGenRootTypes['Product']; // Product!
    login: NexusGenRootTypes['AuthType']; // AuthType!
    product: NexusGenRootTypes['Product']; // Product!
    register: NexusGenRootTypes['AuthType']; // AuthType!
    requestOtp: NexusGenRootTypes['AuthType'] | null; // AuthType
    user: NexusGenRootTypes['User']; // User!
    verifyEmail: NexusGenRootTypes['AuthType']; // AuthType!
  }
  Product: { // field return type
    createdBy: NexusGenRootTypes['User'] | null; // User
    creatorId: string; // String!
    id: string; // String!
    name: string; // String!
    price: number; // Float!
  }
  Query: { // field return type
    product: NexusGenRootTypes['Product']; // Product!
    products: NexusGenRootTypes['Product'][]; // [Product!]!
  }
  User: { // field return type
    email: string; // String!
    id: string; // String!
    isVerified: boolean; // Boolean!
    otp: string; // String!
    password: string; // String!
    refreshToken: string; // String!
    username: string; // String!
  }
}

export interface NexusGenFieldTypeNames {
  AuthType: { // field return type name
    message: 'String'
    token: 'String'
    user: 'User'
  }
  Mutation: { // field return type name
    accessToken: 'AuthType'
    createProduct: 'Product'
    login: 'AuthType'
    product: 'Product'
    register: 'AuthType'
    requestOtp: 'AuthType'
    user: 'User'
    verifyEmail: 'AuthType'
  }
  Product: { // field return type name
    createdBy: 'User'
    creatorId: 'String'
    id: 'String'
    name: 'String'
    price: 'Float'
  }
  Query: { // field return type name
    product: 'Product'
    products: 'Product'
  }
  User: { // field return type name
    email: 'String'
    id: 'String'
    isVerified: 'Boolean'
    otp: 'String'
    password: 'String'
    refreshToken: 'String'
    username: 'String'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createProduct: { // args
      name: string; // String!
      price: number; // Float!
    }
    login: { // args
      emailOrUsername: string; // String!
      password: string; // String!
    }
    product: { // args
      id: string; // String!
      name?: string | null; // String
      price?: number | null; // Float
    }
    register: { // args
      email: string; // String!
      password: string; // String!
      username: string; // String!
    }
    user: { // args
      email?: string | null; // String
      username?: string | null; // String
    }
    verifyEmail: { // args
      otp: string; // String!
    }
  }
  Query: {
    product: { // args
      id: string; // String!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: any;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}